### ISSUE TITLE
Add script/tool to update hashes of CMakeLists.txt and/or use develop

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#164]
As the title says, we should make a tool to create/update the CMakeLists.txt so that it doesn't need to be hand edited.

**Comment by CoryMartin-NOAA** [comment]
After discussion with @guillaumevernieres this will likely be based heavily on a tool developed for SOCA by @travissluka.
The idea is we would have:

- develop branch with develop in JEDI repos
- a stable branch with stable hash commits for JEDI repos
- a release branch with manually specified hash commits to create tags/hash commits for the global workflow

**Comment by travissluka** [comment]
@CoryMartin-NOAA feel free to steal what you need from

- https://github.com/JCSDA-internal/soca/blob/5014fe33be32aaaba4b7ec480bd6bad0e39fb841/.travis.yml#L132
- https://github.com/JCSDA-internal/soca/blob/develop/.github/travisci/stable_mark.sh
- https://github.com/JCSDA-internal/soca/blob/develop/.github/travisci/stable_commit.sh

The `stable_mark.sh` script is more complicated than you need, since my build process on TravisCI is weird and caches upstream components and doesn't rebuild them when possible.

**Comment by CoryMartin-NOAA** [comment]
thanks @travissluka these will be very useful!

**Comment by CoryMartin-NOAA** [comment]
Work for this will be in [feature/update_hashes](https://github.com/NOAA-EMC/GDASApp/tree/feature/update_hashes)

**Comment by CoryMartin-NOAA** [comment]
Travis's script added to this branch by Guillaume in #169

**Comment by CoryMartin-NOAA** [comment]
This will be closed by #208

**Comment by CoryMartin-NOAA** [comment]
Closed through #208
