### ISSUE TITLE
Add and test snow DA increment application code

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#200]
- [x] Include to GDASApp the add JEDI increment code
- [x] test code offline that has been built with GDASApp
- [x] add ctest to test increment add code

**Comment by jiaruidong2017** [comment]
Because there is no repo for `add_jedi_incr` available, we have several options: 

1. We create and maintain a github repo; 
2. Ask Clara to create and maintain a github repo; 
3. We need to make a copy of the add_jedi_incr package into GDASApp.

If the option 3 is selected, where should the `add_jedi_incr` package be saved at? 

- ${PROJECT_SOURCE_DIR}
- ${PROJECT_SOURCE_DIR}/test/land/
- ${PROJECT_SOURCE_DIR}/ush/land/

For the `${PROJECT_SOURCE_DIR}` option, it is easy to build by:
ADD: “add_subdirectory(land-jediincr)” into “CMakeLists.txt”
In `build.sh` 
ADD: builddirs="fv3-jedi soca iodaconv land-imsproc land-jediincr"
I doubt this option is allowed, because it is home directory for GDASApp. 

For the `${PROJECT_SOURCE_DIR}/test/land/` option, I need help on how to build this package?
In `build.sh` try the following (but not working)
```
  cd $dir_root/test/land/land-jediincr
  make -j ${BUILD_JOBS:-6} VERBOSE=$BUILD_VERBOSE
  cd $dir_root
```

**Comment by jiaruidong2017** [comment]
There is a bug in the "https://github.com/NOAA-PSL/land-apply_jedi_incr.git"  TAG a12a046. When building this package in GDASApp, we got the following errors. I fixed the bug and created a PR to PSL for them to merge the PR. 
```
-- ---------------------------------------------------------
-- Adding bundle project land-jediincr
-- Cloning land-jediincr from https://github.com/NOAA-PSL/land-apply_jedi_incr.git into /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.5/land-jediincr...
-- /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.5/land-jediincr retrieved.
-- Updating land-jediincr to TAG a12a046...
-- git fetch --all @ /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.5/land-jediincr
-- git fetch --all --tags @ /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.5/land-jediincr
-- git checkout a12a046 @ /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.5/land-jediincr
-- ---------------------------------------------------------
-- [jediincr] (2022.10) [a12a046]
-- Feature TESTS enabled
CMake Error at land-jediincr/cmake/compiler_flags_Intel_Fortran.cmake:2:
  Parse error.  Expected "(", got newline with text "

  ".
Call Stack (most recent call first):
  land-jediincr/cmake/jediincr_compiler_flags.cmake:16 (include)
  land-jediincr/CMakeLists.txt:16 (include)

-- Configuring incomplete, errors occurred!
```

**Comment by jiaruidong2017** [comment]
For now, I added my branch with bugfix to build `apply_jedi_incr` in `GDASApp` for the test as below: 

```
#  ecbuild_bundle( PROJECT land-jediincr GIT "https://github.com/NOAA-PSL/land-apply_jedi_incr.git"  TAG a12a046 )
  ecbuild_bundle( PROJECT land-jediincr GIT "https://github.com/jiaruidong2017/land-apply_jedi_incr.git"  BRANCH bugfix )
```

Once the PSL merges my updates, I will switch to use PSL repo as above.

**Comment by jiaruidong2017** [comment]
@CoryMartin-NOAA The `add_jedi_incrpply_jedi_incr` script uses `srun` to submit job. Would you please let me know where in GDASApp to define and how to apply the SBATCH (e.g., account, queue, etc.) settings? Thanks.

**Comment by CoryMartin-NOAA** [comment]
@jiaruidong2017 for now, I think we will operate under the assumption that the user will have the `SBATCH_*` variables set before running the tests. So, don't worry about that for now and your `srun` command should just be `srun --export=All -n 6 ./exe.x`. Do you know about the SLURM environment variables?

```
export SLURM_ACCOUNT=da-cpu
export SALLOC_ACCOUNT=$SLURM_ACCOUNT
export SBATCH_ACCOUNT=$SLURM_ACCOUNT
export SLURM_QOS=debug
```

**Comment by jiaruidong2017** [comment]
Thanks @CoryMartin-NOAA Yes, I know these SLURM environment variables. Do you mean I need to first set up these SLUMR variables before I submit my ctest with srun command?

**Comment by CoryMartin-NOAA** [comment]
yes
