### ISSUE TITLE
JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY failing on Orion

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/GDASApp#391]
> All 48 ctests pass on Orion with the exception of `test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_VRFY`. This test initially failed because the job exceeded the specified 5 minute wall clock limit. The job still failed after increasing the wall clock limit. The error, though, is not a wall clock issue. The job failed with a socket error
> 
> ```
>   File "/work2/noaa/da/python/opt/core/miniconda3/4.6.14/envs/eva/lib/python3.9/socket.py", line 832, in create_connection
>     sock.connect(sa)
> TimeoutError: [Errno 110] Connection timed out
> ```
> 
> All 48 tests pass on Hera. Test `test_gdasapp_soca_JGDAS_GLOBAL_OCEAN_ANALYSIS_BMAT_VRFY` finishes in Hera in about 43 seconds. Not sure why the test runs longer and fails on Orion.

Thanks @RussTreadon-NOAA  for reporting the issue. @AndrewEichmann-NOAA or myself will have a look at it early next week.

_Originally posted by @guillaumevernieres in https://github.com/NOAA-EMC/GDASApp/issues/388#issuecomment-1464948419_

**Comment by CoryMartin-NOAA** [comment]
I believe this can be closed, let me know if it should be reopened, it was due to @RussTreadon-NOAA not having shapefiles already staged in his home directory. We should potentially open a new issue along the lines of "have the GDASApp EVA modulefile point to centralized shapefiles" if we think that is a good idea.
